config/routes.rb
Rails.application.routes.draw do
  resources :humen
  resources :categories
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :humen
end

app/models/human.rb
class Human < ApplicationRecord
  belongs_to :category

  def problem_html
    markdown.render problem
  end

  def solution_html
    CodeRay.scan(solution, :ruby).div(:line_numbers => :table)
  end

  def aim_html
    markdown.render aim
  end

  def input
    stdin, @sample = Eval.random_gets(source_type)
    Eval.wrap_eval stdin, solution
    @sample
  end

  def result
    Eval.wrap_eval Eval.repeat_gets(@sample), solution
  end

  private

  def markdown
    @markdown ||= Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/humen_controller.rb
class HumenController < ApplicationController
  before_action :set_human, only: [:show, :edit, :update, :destroy]

  # GET /humen
  # GET /humen.json
  def index
    @humen = Human.all
  end

  # GET /humen/1
  # GET /humen/1.json
  def show
    @solution = CodeRay.scan(@human.solution, :ruby).div(:line_numbers => :table)
  end

  # GET /humen/new
  def new
    @human = Human.new
  end

  # GET /humen/1/edit
  def edit
  end

  # POST /humen
  # POST /humen.json
  def create
    @human = Human.new(human_params)

    respond_to do |format|
      if @human.save
        format.html { redirect_to @human, notice: 'Human was successfully created.' }
        format.json { render :show, status: :created, location: @human }
      else
        format.html { render :new }
        format.json { render json: @human.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /humen/1
  # PATCH/PUT /humen/1.json
  def update
    respond_to do |format|
      if @human.update(human_params)
        format.html { redirect_to @human, notice: 'Human was successfully updated.' }
        format.json { render :show, status: :ok, location: @human }
      else
        format.html { render :edit }
        format.json { render json: @human.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /humen/1
  # DELETE /humen/1.json
  def destroy
    @human.destroy
    respond_to do |format|
      format.html { redirect_to humen_url, notice: 'Human was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_human
      @human = Human.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def human_params
      params.require(:human).permit(:problem, :solution, :aim, :expected_time, :order, :category_id, :source_type)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/humen_helper.rb
module HumenHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
  <% @category.humen.each do |h| %>
    <hr>
    <p>
      <strong>Order:</strong>
      <%= h.order %>
      <%= link_to 'Show', h %>
    </p>

    <p>
      <strong>Problem:</strong>
      <%= h.problem_html.html_safe %>
    </p>

    <p>
      <strong>Expected time:</strong>
      <%= h.expected_time %> min
    </p>

    <p>
      <strong>Aim:</strong>
      <%= h.aim_html.html_safe %>
    </p>

    <p>
      <strong>Solution:</strong>
      <%= h.solution_html.html_safe %>
    </p>

    <p>
      <strong>Result:</strong>
      <% h.input %>
      <pre><%= h.result %></pre>
    </p>
<% end %>

</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/categories/show.md.erb
<% @category.humen.each do |h| %>
## 課題<%= h.order %> 制限時間<%= h.expected_time %>分

### 問題文

<%= h.problem.html_safe %>

### ねらい

<%= h.aim %>

<details>
<summary>解答例</summary>

```ruby
<%= raw h.solution.chomp %>
```

</details>

<% end %>

app/views/humen/_form.html.erb
<%= form_with(model: human, local: true) do |form| %>
  <% if human.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(human.errors.count, "error") %> prohibited this human from being saved:</h2>

      <ul>
        <% human.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :problem %>
    <%= form.text_area :problem %>
  </div>

  <div class="field">
    <%= form.label :solution %>
    <%= form.text_area :solution %>
  </div>

  <div class="field">
    <%= form.label :aim %>
    <%= form.text_area :aim %>
  </div>

  <div class="field">
    <%= form.label :expected_time %>
    <%= form.number_field :expected_time %>
  </div>

  <div class="field">
    <%= form.label :order %>
    <%= form.number_field :order %>
  </div>

  <div class="field">
    <%= form.label :category %>
    <%#= form.text_field :category %>
    <%#= form.select :sport_id, options_for_select(Category.all.map{|s|[s.name, s.id]}) %>

    <%= form.collection_select(:category_id, Category.all, :id, :name) %>
  </div>

  <div class="field">
    <%= form.label :source_type %>
    <%= form.text_field :source_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/humen/edit.html.erb
<h1>Editing Human</h1>

<%= render 'form', human: @human %>

<%= link_to 'Show', @human %> |
<%= link_to 'Back', humen_path %>

app/views/humen/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Humen</h1>

<table>
  <thead>
    <tr>
      <th>Category</th>
      <th>Order</th>
      <th>Aim</th>
      <th>Problem</th>
      <th>Solution</th>
      <th>Expected time</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @humen.each do |human| %>
      <tr>
        <td><%= link_to human.category.name, human.category %></td>
        <td><%= human.order %></td>
        <td><%= human.aim_html.html_safe %></td>
        <td><%= human.problem_html.html_safe %></td>
        <td><%= human.solution_html.html_safe %></td>
        <td><%= human.expected_time %></td>
        <td><%= link_to 'Show', human %></td>
        <td><%= link_to 'Edit', edit_human_path(human) %></td>
        <td><%= link_to 'Destroy', human, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Human', new_human_path %>

app/views/humen/new.html.erb
<h1>New Human</h1>

<%= render 'form', human: @human %>

<%= link_to 'Back', humen_path %>

app/views/humen/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Problem:</strong>
  <%= @human.problem_html.html_safe %>
</p>

<p>
  <strong>Solution:</strong>
  <%= @human.solution_html.html_safe %>
</p>

<p>
  <strong>Inputs:</strong>
  <% @human.input.each do |i| %>
    <%= i %><br>
  <% end %>
</p>

<p>
  <strong>Result:</strong>
  <pre><%= @human.result %></pre>
</p>

<p>
  <strong>Aim:</strong>
  <%= @human.aim_html.html_safe %>
</p>

<p>
  <strong>Expected time:</strong>
  <%= @human.expected_time %>
</p>

<p>
  <strong>Order:</strong>
  <%= @human.order %>
</p>

<p>
  <strong>Category:</strong>
  <%= @human.category.name %>
</p>

<%= link_to 'Edit', edit_human_path(@human) %> |
<%= link_to 'Back', humen_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RubyOfAja</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= link_to 'Categories', categories_path %>
    <%= link_to 'Humen', humen_path %>
    <%= yield %>
  </body>
</html>